[build-system]
requires = [ "setuptools", "wheel",]
build-backend = "setuptools.build_meta"

[project]
name = "arthexis"
version = "0.2.0"
description = "Power & Energy Infrastructure"
requires-python = ">=3.10"
license = "GPL-3.0-only"
classifiers = [ "Programming Language :: Python :: 3", "Framework :: Django",]
dependencies = [ "amqp==5.3.1", "anyio==4.12.0", "asgiref==3.11.0", "attrs==25.3.0", "autobahn==24.4.2", "Automat==25.4.16", "billiard==4.2.4", "black==25.12.0", "bleach==6.3.0", "boto3==1.36.23", "botocore==1.36.23", "celery==5.5.3", "certifi==2025.11.12", "cffi==2.0.0", "channels-redis==4.3.0", "channels==4.3.2", "charset-normalizer==3.4.4", "click-didyoumean==0.3.1", "click-plugins==1.1.1.2", "click-repl==0.3.0", "click==8.3.1", "colorama==0.4.6", "constantly==23.10.4", "cron-descriptor==2.0.6", "cryptography==45.0.5", "daphne==4.2.1", "defusedxml==0.7.1", "diff-match-patch==20241021", "django-celery-beat==2.8.1", "django-debug-toolbar==6.1.0", "django-import-export==4.3.14", "django-mermaid==0.1.0", "django-object-actions==5.0.0", "django-otp==1.6.3", "django-timezone-field==7.2.1", "Django==5.2.9", "dnspython==2.7.0", "docutils==0.22.3", "geckodriver-autoinstaller==0.1.0", "gpiozero==2.0.1; sys_platform == \"linux\"", "graphviz==0.21", "h11==0.16.0", "httpcore==1.0.9", "httpx==0.28.1", "hyperlink==21.0.0", "idna==3.11", "incremental==24.11.0", "jmespath==1.0.1", "kombu==5.5.4", "Markdown==3.10", "mdx_truly_sane_lists==1.3", "mkdocs==1.6.1", "mfrc522==0.0.7; sys_platform == \"linux\"", "outcome==1.3.0.post0", "packaging==25.0", "pillow==12.0.0", "plyer==2.1.0; sys_platform == \"win32\"", "prompt_toolkit==3.0.52", "psutil==7.1.3", "psycopg-binary==3.3.2", "psycopg==3.3.2", "pyasn1==0.6.1", "pyasn1_modules==0.4.2", "pycparser==2.23", "pyOpenSSL==25.1.0", "PySocks==1.7.1", "pytest-django==4.11.1", "pytest==9.0.2", "python-crontab==3.3.0", "python-dateutil==2.9.0.post0", "python-dotenv==1.2.1", "qrcode==8.2", "redis==7.1.0", "reportlab==4.4.7", "requests==2.32.5", "s3transfer==0.11.1", "selenium==4.34.2", "service-identity==24.2.0", "setuptools==80.9.0", "six==1.17.0", "smbus2==0.5.0", "sniffio==1.3.1", "sortedcontainers==2.4.0", "sqlparse==0.5.4", "tablib==3.9.0", "tinycss2==1.5.1", "toml==0.10.2", "trio-websocket==0.12.2", "trio==0.30.0", "twine==6.1.0", "Twisted==25.5.0", "txaio==25.9.2", "typing_extensions==4.14.1", "tzdata==2025.3", "urllib3==2.5.0", "vine==5.1.0", "wcwidth==0.2.14", "webauthn==2.7.0", "webencodings==0.5.1", "websocket-client==1.8.0", "websockets>=15,<16", "whitenoise==6.11.0", "wsproto==1.3.2", "zope.interface==8.1.1",]
[[project.authors]]
name = "Rafael J. GuillÃ©n-Osorio"
email = "tecnologia@gelectriic.com"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Repository = "https://github.com/arthexis/arthexis"
Homepage = "https://arthexis.com"

[tool.setuptools]
packages = { find = { where = ["."] } }
include-package-data = true

[tool.setuptools.package-data]
"apps.core" = ["**/*"]
"apps.awg" = ["**/*"]
"apps.aws" = ["**/*"]
"apps.links" = ["**/*"]
"apps.nodes" = ["**/*"]
"apps.ocpp" = ["**/*"]
"apps.sites" = ["**/*"]
"apps.protocols" = ["**/*"]
"apps.repos" = ["**/*"]
"apps.sigils" = ["**/*"]
"apps.selenium" = ["**/*"]
"apps.teams" = ["**/*"]
"apps.vehicle" = ["**/*"]
"apps.locale" = ["**/*"]
"apps.docs" = ["**/*"]
"apps.wikis" = ["**/*"]
"apps.widgets" = ["**/*"]
"apps.release" = ["**/*"]
"apps.sensors" = ["**/*"]
config = ["**/*"]

[tool.pytest.ini_options]
markers = [
    "timeout: mark tests that enforce runtime limits",
]
DJANGO_SETTINGS_MODULE = "config.settings"
